/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function. dffddf
  ******************************************************************************
*/

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdio.h>
#include "stm32f0xx.h"
#include "sct.h"



int main(void)
{
	sct_init();

	sct_led(0x7A5C36DE);

	for (volatile uint32_t j = 0; j<31; j++) {};




    while(1){
    	uint32_t i,j;
    	for (i = 0; i < 1000; i++)
    	{
    		sct_value(i);
        	for(j = 0; j < 100000; j++){}

    	}



    }
}
