/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdio.h>
#include "stm32f0xx.h"

int main(void)
{
	RCC->AHBENR |= RCC_AHBENR_GPIOAEN;                   //zapnuti hodin
	GPIOA->MODER |= GPIO_MODER_MODER5_0;                 //

	uint8_t pole[32] = {1,0,1,0,1,0,0,1,1,1,0,1,1,1,0,1,1,1,0,0,1,0,1,0,1}; //morseovka sos
	//  GPIOA->BSRR = (1<<5); // set
	//  GPIOA->BRR = (1<<5); // reset
	//  GPIOA->ODR ^= (1<<5); // toggle

	//blikani
/*
	for(;;)
		{
		  GPIOA->ODR ^= (1<<5); // toggle
		  for (volatile uint32_t i = 0; i < 100000; i++) {}
		};
*/
/*
	for(;;)
	    {
			if(pole[j]==1)
			  {GPIOA->BSRR = (1<<5);}
			else
			  {GPIOA->BRR = (1<<5);}

			for(volatile uint32_t i = 0; i < 100000; i++)
				;

			j++;
			if (j == sizeof(pole)) j = 0;
		}
*/
	uint32_t SOS = 0b1010100111011101110010101;   //morseovka SOS
    for(;;)
        {
	    for (uint32_t i = 0; i < 32; i++){
		    if ((SOS<<i) & 0x80000000)
		        {     //bitovy posuv a zkoumani zda-li jednicka nebo 0
			    GPIOA->BSRR = (1<<5); // set
			    }
			else
			    {
				GPIOA->BRR = (1<<5); // reset
			    }
			for (volatile uint32_t t = 0; t < 100000; t++) {}
			}
			for (volatile uint32_t j = 0; j < 900000; j++) {} //delsi cekani
    }

}
